name: CP-AMM-SDK

on:
  pull_request:
    branches:
      - main

env:
  SOLANA_CLI_VERSION: 1.16.1
  NODE_VERSION: 18.20.6
  ANCHOR_CLI_VERSION: 0.29.0

jobs:
  sdk_unit_test:
    runs-on: ubuntu-latest
    needs: program_changed_files
    if: needs.program_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      # Install pnpm
      - uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 9.5.0 # Optional: specify a pnpm version
      # Install rust + toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v1
      # Cache node_modules
      - uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: ./ts-client/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./ts-client/package-lock.json') }}
      # Testing
      - run: pnpm install
        shell: bash
      - run: pnpm test
        shell: bash
